remote_theme: just-the-docs/just-the-docs@v0.10.2

title: Numix Circle for Sailfish OS
description: Numix Circle for Sailfish OS

url: "https://uithemer.github.io"
baseurl: "/harbour-themepack-numix-circle"
repository: uithemer/harbour-themepack-numix-circle

search_enabled: false

aux_links:
  "Numix Circle on GitHub":
    - "https://github.com/uithemer/harbour-themepack-numix-circle"

exclude:
  - appicons/
  - other/
  - qml/
  - rpm/
  - src/
  - theme/
  - translations/
  - .sfdk/
  - RPMS/
  - LICENSE
  - "*.desktop"
  - "*.pro"
  - "*.pro.user"
  - .gitignore
  - .jekyll-cache/
  - vendor/
